### ISSUE TITLE
Problem loading Frontend

### ISSUE THREAD

**Issue by WebThor** [steptools/StepNCViewer#1]
After downloading the StepNCViewer I tried to set it up like described at the readme file. But I always receive following massage from the tool when landing on the Frontend:

> CADjs@2.0.0 start-dev /root/cad.js
> node src/server/api_server.js -e development

info: CAD.js API Server listening on: 8080
info:   Redis Connected.
info: Configuring auth/auth plugin: permit
info:   Setting User-Validation function
info:   Setting User-Authorization function
info: Configuring storage plugin: filesystem
info:   Assembly Root: /root/cad.js/data
info:   NC Root: /root/cad.js/data
GET /cad.js?resource_url=/data/cutter/index.xml 304 - - 101.958 ms
GET /js/main.css 304 - - 47.866 ms
GET /js/main.js 304 - - 72.403 ms

and then finish. The tool is not showing anything on 127.0.0.1:8080..
Is there a bug or am I doing something wrong?

**Comment by X-sam** [comment]
Interface is at /stepnc. Not a bug.
