### ISSUE TITLE
Title of data folder must be lowercase

### ISSUE THREAD

**Issue by nicholasfay** [steptools/StepNCViewer#102]
Refers to the folders within the data folder but pull request #109 might have made this less prevalent

**Comment by ian-h-chamberlain** [comment]
I don't get any errors with this as long as my pathmap.json file contains the correct case – anything else needed to reproduce?

**Comment by ian-h-chamberlain** [comment]
Additionally, even if my pathmap.json's case does not match the folder name's case, I seem to be able to load the projects without any issues.
