### ISSUE TITLE
If two models are named the same issues arise when switching between them.

### ISSUE THREAD

**Issue by funnymanpatrick** [steptools/StepNCViewer#103]
How to reproduce:
have two models named model.stpnc with different project names
load one project
load the other project
get an error

This might be a lower level problem

**Comment by ian-h-chamberlain** [comment]
This seems to be a problem with the sidebar view, or at least something that the sidebar view uses

**Comment by ian-h-chamberlain** [comment]
This seems to have been fixed by some other changes made at some point.
