### ISSUE TITLE
Play/pause button doesn't update properly when two projects are open

### ISSUE THREAD

**Issue by Sjbeale** [steptools/StepNCViewer#115]
when you play a project it stops the other projects without updating the play/pause button to reflect that it's paused. then if you pause and play another project, pausing the original project that was stopped will update a playing project to display the play button.

**Comment by Sjbeale** [comment]
Also if you pause the playing project instead of pausing the original project, the play button will display for the original object but pressing it will do nothing.

**Comment by funnymanpatrick** [comment]
Low priority. The supported use cases involve one instance per model so this won't come up

**Comment by X-sam** [comment]
Server is going to be refactored so it has a 1-1 relationship with a file. This nullifies the issue presented here.
