### ISSUE TITLE
App doesn't seem to die properly on windows

### ISSUE THREAD

**Issue by X-sam** [steptools/StepNCViewer#121]
Always have to go into task mangler to kill the process...

**Comment by funnymanpatrick** [comment]
current workaround is using Git Bash, problem persists with the windows command promopt

**Comment by cabral450** [comment]
there is no problem on linux either, any word from a mac user?
@ian-h-chamberlain @UuqV

**Comment by nicholasfay** [comment]
Works on mac

**Comment by funnymanpatrick** [comment]
Determined to not be our problem
