### ISSUE TITLE
After jumping to workingstep, sometimes part geometry does not render

### ISSUE THREAD

**Issue by ian-h-chamberlain** [steptools/StepNCViewer#173]
To reproduce, select workingstep 34 and reload the client. Then jump to step 33. Toolpath geometry and tool display, but the part itself is not rendered until the client is reloaded.

**Comment by Sjbeale** [comment]
This appears to only happen to the step previous to the workingstep that was active when the page was loaded.

**Comment by Sjbeale** [comment]
This also only happens if the active working step when the page was loaded is not inside a selective..
