### ISSUE TITLE
When changing workingsteps bounding box only encompasses the tool

### ISSUE THREAD

**Issue by funnymanpatrick** [steptools/StepNCViewer#175]
@UuqV #170 #163 

What web of spaghetti have I uncovered?

**Comment by ian-h-chamberlain** [comment]
Possibly related, the bounding box sometimes only encompasses the fixture (this happened on workingstep 22 for me after pressing next a number of times)

**Comment by ian-h-chamberlain** [comment]
This seems partially related to #85

**Comment by funnymanpatrick** [comment]
#196
