### ISSUE TITLE
properties pane needs styling

### ISSUE THREAD

**Issue by X-sam** [steptools/StepNCViewer#183]

**Comment by ian-h-chamberlain** [comment]
Also add additional info: workingstep type / other info available in STEP-NC Machine now

**Comment by X-sam** [comment]
Additionally properties icons don't match with #226 tree changes.

**Comment by williamgrh** [comment]
This is half completed in #281

**Comment by nicholasfay** [comment]
#295 updates the properties pane even further

**Comment by williamgrh** [comment]
#298 finished this

**Comment by williamgrh** [comment]
#299 Adds backtracking functionality
