### ISSUE TITLE
If toolpaths are the same shape but rotated they will not load

### ISSUE THREAD

**Issue by funnymanpatrick** [steptools/StepNCViewer#256]
In impeller several toolpaths are the same but from different angles. The first time one is loaded a toolpath is requested but afterwards any of those workingsteps will use the first tool path (tool moves correctly)

**Comment by funnymanpatrick** [comment]
looks like the annotations have the same name and return value. Likely has to do with how the names are determined

**Comment by X-sam** [comment]
They are the same geometry just rotated. Xform isn't being checked in
applydelta

On Fri, Jul 8, 2016 at 1:49 PM, Patrick Hesselbach <notifications@github.com

**Comment by ian-h-chamberlain** [comment]
This appears to have been fixed by #264
