### ISSUE TITLE
part doesn't load delta transforms properly.

### ISSUE THREAD

**Issue by X-sam** [steptools/StepNCViewer#262]
On 3-axis machines with moving bases such as the okuma, the geometry should move with the fixture. It doesn't move at all in the current version.

**Comment by ian-h-chamberlain** [comment]
I'm having trouble repro, are there any other machines you notice it on?

**Comment by X-sam** [comment]
If you watch the model, the base of the machine moves, the fixture moves,
and the part remains stationary. It should move with the fixture.
