### ISSUE TITLE
Tolerance pane sometimes appears empty

### ISSUE THREAD

**Issue by ian-h-chamberlain** [steptools/StepNCViewer#290]
This happens on models that include tolerance/workpiece data and is usually fixed with a reload

**Comment by ian-h-chamberlain** [comment]
This appears to be a server-side issue

**Comment by nicholasfay** [comment]
This is an issue with the underlying function GetWorkpieceCount

**Comment by nicholasfay** [comment]
Fixed with pull request #294

**Comment by ian-h-chamberlain** [comment]
This issue still occurs sometimes

**Comment by nicholasfay** [comment]
Should be fixed now with new maker release 12.46
