### ISSUE TITLE
When using 3-axis boxy with 7 setups, attempting to go to WS 27 results in just moving the current workingstep along slightly

### ISSUE THREAD

**Issue by funnymanpatrick** [steptools/StepNCViewer#296]

**Comment by funnymanpatrick** [comment]
Likely a machinestate or data issue

**Comment by funnymanpatrick** [comment]
also occurs when a manual setws command is sent

**Comment by ian-h-chamberlain** [comment]
With the new master boxy, this happens on the first workingstep of Setups 2, 3, and 5 (steps 4, 11, and 22, respectively)

Also happens on steps 21 and 32
