### ISSUE TITLE
Desktop view does not always expand to full width

### ISSUE THREAD

**Issue by ian-h-chamberlain** [steptools/StepNCViewer#31]
To see this, begin with a full-sized desktop window, then resize until the view is narrow enough to switch to a mobile view. Then, resize back to full size – the CAD.js area will typically (in my case) stop expanding right at some point, leaving a white bar on the far right side of the screen.

**Comment by funnymanpatrick** [comment]
Can not reproduce on my system, may be a mac specific issue.
Maybe test with linux @Roceso1337

**Comment by ian-h-chamberlain** [comment]
I will tackle this once I finish my current task

**Comment by ian-h-chamberlain** [comment]
This has been fixed in the latest update somehow.
