### ISSUE TITLE
Tool assemblies do not load all parts of geometry

### ISSUE THREAD

**Issue by ian-h-chamberlain** [steptools/StepNCViewer#386]
Newest boxy from PSU displays this

**Comment by ian-h-chamberlain** [comment]
This appears to be caused by not getting all shells from GetGeometryJSON, or could also be because we need more stuff than just getting the tool workpiece id?

**Comment by X-sam** [comment]
Turns out data was technically incorrect. Getting fixed at the lower level.

**Comment by ian-h-chamberlain** [comment]
Fixed with stixsim update
