### ISSUE TITLE
Display upcoming tolerances in sections instead of workpieces

### ISSUE THREAD

**Issue by ian-h-chamberlain** [steptools/StepNCViewer#406]

**Comment by williamgrh** [comment]
Tolerance sidebar pane should have two sections. One for tolerances on the active workingstep and one for 'upcoming' tolerances (tolerances in the next 3 workingsteps).

**Comment by cabral450** [comment]
checkout at upcomingtolerances branch
it works on a working step before one with tolerances (to display upcoming tolerances)
but then it shows active tolerances as upcoming tolerances (fix)
