### ISSUE TITLE
Go straight to active workingstep instead of looping through to find it

### ISSUE THREAD

**Issue by ian-h-chamberlain** [steptools/StepNCViewer#430]
This should cut down on load times by a lot and makes more sense

**Comment by nicholasfay** [comment]
This can be done by making an parallel array of workingstep ids on the server so that .mtc workingsteps can have the line numbers associated with ids and then GoToWS(id) can be used to catch up the simulation rather than looping

**Comment by ian-h-chamberlain** [comment]
Fixed in #435
