### ISSUE TITLE
Toolpaths load upside-down and workingstep changes are buggy

### ISSUE THREAD

**Issue by ian-h-chamberlain** [steptools/StepNCViewer#438]
This seems to happen only on the second workingstep

**Comment by funnymanpatrick** [comment]
fixed in MTConnect branch, issue involved Okuma machine not recognizing IF lines as lines

**Comment by X-sam** [comment]
DONT BELIEVE HIS LIES

**Comment by funnymanpatrick** [comment]
I am not cake
