### ISSUE TITLE
tolerance units invalid on 242 files

### ISSUE THREAD

**Issue by X-sam** [steptools/StepNCViewer#550]
Seems to always come back as 'unknown' despite following same codepaths as STEP-NC machine.

**Comment by david-loffredo** [comment]
stix_tag_units does not appear to be called through read_238 if it is an ap242 file, but not clear why it works in the DLL context.    Must be getting called somewhere else to mask this.

**Comment by david-loffredo** [comment]
Fixed within the maker library by @martin-hardwick
