### ISSUE TITLE
babel-loader update breaks deps

### ISSUE THREAD

**Issue by david-loffredo** [steptools/StepNCViewer#556]
The latest babel-loader update to v8 breaks the babel deps.   They have changed to use an @babel naming.   Go through the deps and update.   Forcing to v7 for the moment

**Comment by koenhendriks** [comment]
I'm trying to force to v7 but i can't seem to get it working. do the `babel-cli`, `babel-core` and etc also need to be forced to a specific version ?

**Comment by david-loffredo** [comment]
PR #557 reworks and updates many of the deps to remove "latest" specs that would drift over time.  Babel is still locked at 6, but everything should now build properly.
